name: mwazbet_elsalah
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ^3.11.1

dependencies:
  audioplayers: ^6.6.0
  cloud_firestore: ^6.3.0
  country_picker: ^2.0.27
  country_state_city_pro: ^0.0.6
  country_state_picker: ^0.1.2
  curved_navigation_bar: ^1.0.6
  dio: ^5.9.2
  easy_localization: ^3.0.8
  firebase_auth: ^6.4.0
  firebase_core: ^4.7.0
  flex_color_scheme: ^8.4.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_facebook_auth: ^7.1.6
  flutter_local_notifications: ^21.0.0
  flutter_native_splash: ^2.4.7
  flutter_qiblah: ^3.2.0
  flutter_slidable: ^4.0.3
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  google_sign_in: ^7.2.0
  intl: ^0.20.2
  timezone: ^0.11.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audio/
    - assets/images/splash/
    - assets/translations/
flutter_native_splash:
  color: "#000000"

  image: assets/images/splash/splash_transparent.png

  android: true
  ios: true
  fullscreen: true

  android_12:
    color: "#000000"
    image: assets/images/splash/splash_transparent.png
