// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAk4cSVRtU1Odpymgq6HeusoJyIpazOCp8',
    appId: '1:204788388795:web:69a5e80860a8f9c41eaa9e',
    messagingSenderId: '204788388795',
    projectId: 'online-coaching-260ce',
    authDomain: 'online-coaching-260ce.firebaseapp.com',
    storageBucket: 'online-coaching-260ce.firebasestorage.app',
    measurementId: 'G-BMNRY0S1ML',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDR5g1i_-UiQ8be0VRqC0-GFgzPzvv-34',
    appId: '1:204788388795:android:0234c76fba53056f1eaa9e',
    messagingSenderId: '204788388795',
    projectId: 'online-coaching-260ce',
    storageBucket: 'online-coaching-260ce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQ5tRicgKjhpudx-MV4RUTnN6LGBp6OZQ',
    appId: '1:204788388795:ios:a55716330db301d91eaa9e',
    messagingSenderId: '204788388795',
    projectId: 'online-coaching-260ce',
    storageBucket: 'online-coaching-260ce.firebasestorage.app',
    iosBundleId: 'com.example.mwazbetElsalah',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQ5tRicgKjhpudx-MV4RUTnN6LGBp6OZQ',
    appId: '1:204788388795:ios:a55716330db301d91eaa9e',
    messagingSenderId: '204788388795',
    projectId: 'online-coaching-260ce',
    storageBucket: 'online-coaching-260ce.firebasestorage.app',
    iosBundleId: 'com.example.mwazbetElsalah',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAk4cSVRtU1Odpymgq6HeusoJyIpazOCp8',
    appId: '1:204788388795:web:999b99e8d045580b1eaa9e',
    messagingSenderId: '204788388795',
    projectId: 'online-coaching-260ce',
    authDomain: 'online-coaching-260ce.firebaseapp.com',
    storageBucket: 'online-coaching-260ce.firebasestorage.app',
    measurementId: 'G-Z7SCVESYT0',
  );
}
